server:
  port: 8082

logging:
  level:
    ROOT: INFO
    az.elgunb.shopping: DEBUG

spring:
  application:
    name: ms-order
  liquibase:
    change-log: classpath:db/changelog-master.xml
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/shop_order
    username: order
    password: order123
    hikari:
      poolName: MsOrderHikariPool
      auto-commit: false
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.format_sql: true
  cloud:
    stream:
      source: sendEmailNotificationEvent;sendPhoneOrderEvent
      function:
        definition: receiveOrderStatusChangeEvent
      kafka:
        binder:
          brokers: localhost:29092
      bindings:
        sendEmailNotificationEvent-out-0:
          destination: email-notification
        sendPhoneOrderEvent-out-0:
          destination: phone-order
        receiveOrderStatusChangeEvent-in-0:
          destination: phone-order-status-change

application:
  swagger:
    enabled: true
    base-package: "az.elgunb.shopping.order.controller"
    paths: "/.*"
    apiInfo:
      version: 1.0
      title: "Ms-Order Rest API"
      description: "Spring Boot REST API for Ms-Order"
  security:
    authentication:
      jwt:
        base64-secret: V2pOV2FHUnRSbmRaV0d4M1dWaEthbHBYZUd0YVYzaHdaRzFXZVdWWVRqVmpNMUpzWWxkR2QyTklUbXhaTTBwc1pFZDBiR1ZWUW10YVdGbHE=
  filter:
    logging:
      skipped-urls: /actuator/health, /v2/api-docs/**, /v3/api-docs/**, /swagger-resources/**, /webjars/**, /favicon.ico
